import Config

# Configure your database
config :phoenix_starter_kit, PhoenixStarterKit.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "phoenix_starter_kit_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :phoenix_starter_kit, PhoenixStarterKitWeb.Endpoint,
  # Bind to 0.0.0.0 to expose the server to the docker host machine.
  # This makes make the service accessible from any network interface.
  # Change to `ip: {127, 0, 0, 1}` to allow access only from the server machine.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # NOTE: This is a hardcoded secret for DEVELOPMENT ONLY.
  # In production, this is loaded from environment variables.
  # You can generate a new one with: mix phx.gen.secret
  secret_key_base: "xwhIq+DZ3qJt44M7LP1fy2GJFWzzDluFMlPMtCRYK9MZCk2+yhfyCOF8MZQZtFn2",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:phoenix_starter_kit, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:phoenix_starter_kit, ~w(--watch)]},
    esbuild_widget: {Esbuild, :install_and_run, [:widget_extension, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :phoenix_starter_kit, PhoenixStarterKitWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/phoenix_starter_kit_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :phoenix_starter_kit, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Override esbuild widget_extension profile to inject dev API origin for the widget
config :esbuild,
  widget_extension: [
    args: [
      "js/widget_extension.ts",
      "--target=es2017",
      "--define:PHOENIX_STARTER_KIT_API_ORIGIN=\"https://phoenix_starter_kit-dev.peeklabs.com\"",
      "--outfile=../priv/static/assets/widget_extension.js"
    ],
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]
