import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :phoenix_starter_kit, PhoenixStarterKitWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Override esbuild widget_extension profile to inject prod API origin for the widget
config :esbuild,
  widget_extension: [
    args: [
      "js/widget_extension.ts",
      "--target=es2017",
      "--define:PHOENIX_STARTER_KIT_API_ORIGIN=\"https://phoenix_starter_kit.peeklabs.com\"",
      "--outfile=../priv/static/assets/widget_extension.js"
    ],
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]
